-- "characters" and "book_characters" are live tables: adding the nullable FK columns takes an
-- AccessExclusiveLock that Prisma holds until this file commits. The work is milliseconds, the
-- risk is the wait behind a long-running SELECT, so give up after three seconds and retry later.
SET LOCAL lock_timeout = '3s';
SET LOCAL statement_timeout = '60s';

-- CreateEnum
CREATE TYPE "species_name_kind" AS ENUM ('label', 'alias');

-- AlterTable
ALTER TABLE "book_characters" ADD COLUMN     "species_override_id" UUID;

-- AlterTable
ALTER TABLE "characters" ADD COLUMN     "species_id" UUID;

-- CreateTable
CREATE TABLE "species" (
    "id" UUID NOT NULL,
    "key" TEXT,
    "user_id" UUID,
    "name" TEXT COLLATE "uk-UA-x-icu" NOT NULL,
    "normalized_name" TEXT NOT NULL,
    "category_key" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "species_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "species_system_or_custom_check" CHECK (
        ("user_id" IS NULL AND "key" IS NOT NULL AND "category_key" IS NOT NULL)
        OR ("user_id" IS NOT NULL AND "key" IS NULL AND "category_key" IS NULL)
    )
);

-- CreateTable
CREATE TABLE "species_names" (
    "id" UUID NOT NULL,
    "species_id" UUID NOT NULL,
    "locale" TEXT NOT NULL,
    "name" TEXT COLLATE "uk-UA-x-icu" NOT NULL,
    "normalized_name" TEXT NOT NULL,
    "kind" "species_name_kind" NOT NULL,

    CONSTRAINT "species_names_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "species_names_normalized_name_key" ON "species_names"("normalized_name");

-- CreateIndex
CREATE INDEX "species_names_species_id_idx" ON "species_names"("species_id");

-- CreateIndex
CREATE INDEX "book_characters_species_override_id_idx" ON "book_characters"("species_override_id");

-- CreateIndex
CREATE INDEX "characters_species_id_idx" ON "characters"("species_id");

-- Hand-written: Prisma cannot express partial unique indexes. System rows (user_id IS NULL) are unique
-- by key and by normalized name; custom rows are unique by normalized name per owner.
CREATE UNIQUE INDEX "species_system_key_key" ON "species"("key") WHERE "user_id" IS NULL;

CREATE UNIQUE INDEX "species_system_normalized_name_key" ON "species"("normalized_name") WHERE "user_id" IS NULL;

CREATE UNIQUE INDEX "species_user_id_normalized_name_key" ON "species"("user_id", "normalized_name") WHERE "user_id" IS NOT NULL;

-- AddForeignKey
ALTER TABLE "characters" ADD CONSTRAINT "characters_species_id_fkey" FOREIGN KEY ("species_id") REFERENCES "species"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "book_characters" ADD CONSTRAINT "book_characters_species_override_id_fkey" FOREIGN KEY ("species_override_id") REFERENCES "species"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "species" ADD CONSTRAINT "species_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "species_names" ADD CONSTRAINT "species_names_species_id_fkey" FOREIGN KEY ("species_id") REFERENCES "species"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- Hand-written: the 114 system species and their uk/en labels, generated from
-- src/scripts/data/species-catalog.json. ON CONFLICT keeps a re-run a no-op.
INSERT INTO "species" ("id", "key", "name", "normalized_name", "category_key", "updated_at")
SELECT gen_random_uuid(), "seed"."key", "seed"."name", "seed"."normalized_name", "seed"."category_key", CURRENT_TIMESTAMP
FROM (VALUES
    ('human', 'Human', 'human', 'humanoid'),
    ('superhuman', 'Superhuman', 'superhuman', 'humanoid'),
    ('mutant', 'Mutant', 'mutant', 'humanoid'),
    ('clone', 'Clone', 'clone', 'humanoid'),
    ('half_human', 'Half-human', 'half-human', 'humanoid'),
    ('hybrid', 'Hybrid', 'hybrid', 'humanoid'),
    ('artificial_human', 'Artificial human', 'artificial human', 'humanoid'),
    ('elf', 'Elf', 'elf', 'elven'),
    ('high_elf', 'High elf', 'high elf', 'elven'),
    ('wood_elf', 'Wood elf', 'wood elf', 'elven'),
    ('dark_elf', 'Dark elf', 'dark elf', 'elven'),
    ('sea_elf', 'Sea elf', 'sea elf', 'elven'),
    ('ice_elf', 'Ice elf', 'ice elf', 'elven'),
    ('half_elf', 'Half-elf', 'half-elf', 'elven'),
    ('gnome', 'Gnome', 'gnome', 'smallfolk'),
    ('dwarf', 'Dwarf', 'dwarf', 'smallfolk'),
    ('goblin', 'Goblin', 'goblin', 'smallfolk'),
    ('hobgoblin', 'Hobgoblin', 'hobgoblin', 'smallfolk'),
    ('kobold', 'Kobold', 'kobold', 'smallfolk'),
    ('gremlin', 'Gremlin', 'gremlin', 'smallfolk'),
    ('halfling', 'Halfling', 'halfling', 'smallfolk'),
    ('hobbit', 'Hobbit', 'hobbit', 'smallfolk'),
    ('leprechaun', 'Leprechaun', 'leprechaun', 'smallfolk'),
    ('orc', 'Orc', 'orc', 'giants'),
    ('half_orc', 'Half-orc', 'half-orc', 'giants'),
    ('ogre', 'Ogre', 'ogre', 'giants'),
    ('troll', 'Troll', 'troll', 'giants'),
    ('giant', 'Giant', 'giant', 'giants'),
    ('cyclops', 'Cyclops', 'cyclops', 'giants'),
    ('titan', 'Titan', 'titan', 'giants'),
    ('fairy', 'Fairy', 'fairy', 'fae'),
    ('fae', 'Fae', 'fae', 'fae'),
    ('pixie', 'Pixie', 'pixie', 'fae'),
    ('sprite', 'Sprite', 'sprite', 'fae'),
    ('nymph', 'Nymph', 'nymph', 'fae'),
    ('dryad', 'Dryad', 'dryad', 'fae'),
    ('naiad', 'Naiad', 'naiad', 'fae'),
    ('sylph', 'Sylph', 'sylph', 'fae'),
    ('satyr', 'Satyr', 'satyr', 'fae'),
    ('witch', 'Witch', 'witch', 'magic'),
    ('witcher', 'Witcher', 'witcher', 'magic'),
    ('wizard', 'Wizard', 'wizard', 'magic'),
    ('sorcerer', 'Sorcerer', 'sorcerer', 'magic'),
    ('shaman', 'Shaman', 'shaman', 'magic'),
    ('druid', 'Druid', 'druid', 'magic'),
    ('vampire', 'Vampire', 'vampire', 'bloodshifters'),
    ('half_vampire', 'Half-vampire', 'half-vampire', 'bloodshifters'),
    ('dhampir', 'Dhampir', 'dhampir', 'bloodshifters'),
    ('werecreature', 'Werecreature', 'werecreature', 'bloodshifters'),
    ('werewolf', 'Werewolf', 'werewolf', 'bloodshifters'),
    ('shapeshifter', 'Shapeshifter', 'shapeshifter', 'bloodshifters'),
    ('metamorph', 'Metamorph', 'metamorph', 'bloodshifters'),
    ('doppelganger', 'Doppelganger', 'doppelganger', 'bloodshifters'),
    ('ghost', 'Ghost', 'ghost', 'undead'),
    ('apparition', 'Apparition', 'apparition', 'undead'),
    ('poltergeist', 'Poltergeist', 'poltergeist', 'undead'),
    ('zombie', 'Zombie', 'zombie', 'undead'),
    ('skeleton', 'Skeleton', 'skeleton', 'undead'),
    ('mummy', 'Mummy', 'mummy', 'undead'),
    ('lich', 'Lich', 'lich', 'undead'),
    ('revenant', 'Revenant', 'revenant', 'undead'),
    ('ghoul', 'Ghoul', 'ghoul', 'undead'),
    ('specter', 'Specter', 'specter', 'undead'),
    ('demon', 'Demon', 'demon', 'celestial'),
    ('archdemon', 'Archdemon', 'archdemon', 'celestial'),
    ('half_demon', 'Half-demon', 'half-demon', 'celestial'),
    ('imp', 'Imp', 'imp', 'celestial'),
    ('succubus', 'Succubus', 'succubus', 'celestial'),
    ('incubus', 'Incubus', 'incubus', 'celestial'),
    ('angel', 'Angel', 'angel', 'celestial'),
    ('archangel', 'Archangel', 'archangel', 'celestial'),
    ('dragon', 'Dragon', 'dragon', 'mythical'),
    ('wyvern', 'Wyvern', 'wyvern', 'mythical'),
    ('drake', 'Drake', 'drake', 'mythical'),
    ('griffin', 'Griffin', 'griffin', 'mythical'),
    ('phoenix', 'Phoenix', 'phoenix', 'mythical'),
    ('unicorn', 'Unicorn', 'unicorn', 'mythical'),
    ('pegasus', 'Pegasus', 'pegasus', 'mythical'),
    ('basilisk', 'Basilisk', 'basilisk', 'mythical'),
    ('chimera', 'Chimera', 'chimera', 'mythical'),
    ('manticore', 'Manticore', 'manticore', 'mythical'),
    ('centaur', 'Centaur', 'centaur', 'mythical'),
    ('hydra', 'Hydra', 'hydra', 'mythical'),
    ('mermaid', 'Mermaid', 'mermaid', 'aquatic'),
    ('merman', 'Merman', 'merman', 'aquatic'),
    ('siren', 'Siren', 'siren', 'aquatic'),
    ('triton', 'Triton', 'triton', 'aquatic'),
    ('selkie', 'Selkie', 'selkie', 'aquatic'),
    ('animal', 'Animal', 'animal', 'animals'),
    ('sapient_animal', 'Sapient animal', 'sapient animal', 'animals'),
    ('magical_animal', 'Magical animal', 'magical animal', 'animals'),
    ('familiar', 'Familiar', 'familiar', 'animals'),
    ('beastfolk', 'Beastfolk', 'beastfolk', 'animals'),
    ('catfolk', 'Catfolk', 'catfolk', 'animals'),
    ('wolfkin', 'Wolfkin', 'wolfkin', 'animals'),
    ('lizardfolk', 'Lizardfolk', 'lizardfolk', 'animals'),
    ('golem', 'Golem', 'golem', 'constructs'),
    ('automaton', 'Automaton', 'automaton', 'constructs'),
    ('homunculus', 'Homunculus', 'homunculus', 'constructs'),
    ('living_doll', 'Living doll', 'living doll', 'constructs'),
    ('robot', 'Robot', 'robot', 'constructs'),
    ('android', 'Android', 'android', 'constructs'),
    ('cyborg', 'Cyborg', 'cyborg', 'constructs'),
    ('alien', 'Alien', 'alien', 'alien'),
    ('cosmic_being', 'Cosmic being', 'cosmic being', 'alien'),
    ('energy_lifeform', 'Energy lifeform', 'energy lifeform', 'alien'),
    ('symbiote', 'Symbiote', 'symbiote', 'alien'),
    ('hive_organism', 'Hive organism', 'hive organism', 'alien'),
    ('elemental', 'Elemental', 'elemental', 'supernatural'),
    ('djinn', 'Djinn', 'djinn', 'supernatural'),
    ('ifrit', 'Ifrit', 'ifrit', 'supernatural'),
    ('nature_spirit', 'Nature spirit', 'nature spirit', 'supernatural'),
    ('monster', 'Monster', 'monster', 'supernatural'),
    ('otherworldly_being', 'Otherworldly being', 'otherworldly being', 'supernatural')
) AS "seed" ("key", "name", "normalized_name", "category_key")
ON CONFLICT ("key") WHERE "user_id" IS NULL DO NOTHING;

INSERT INTO "species_names" ("id", "species_id", "locale", "name", "normalized_name", "kind")
SELECT gen_random_uuid(), "species"."id", "seed"."locale", "seed"."name", "seed"."normalized_name", 'label'::"species_name_kind"
FROM (VALUES
    ('human', 'uk', 'Людина', 'людина'),
    ('human', 'en', 'Human', 'human'),
    ('superhuman', 'uk', 'Надлюдина', 'надлюдина'),
    ('superhuman', 'en', 'Superhuman', 'superhuman'),
    ('mutant', 'uk', 'Мутант', 'мутант'),
    ('mutant', 'en', 'Mutant', 'mutant'),
    ('clone', 'uk', 'Клон', 'клон'),
    ('clone', 'en', 'Clone', 'clone'),
    ('half_human', 'uk', 'Напівлюдина', 'напівлюдина'),
    ('half_human', 'en', 'Half-human', 'half-human'),
    ('hybrid', 'uk', 'Гібрид', 'гібрид'),
    ('hybrid', 'en', 'Hybrid', 'hybrid'),
    ('artificial_human', 'uk', 'Штучно створена людина', 'штучно створена людина'),
    ('artificial_human', 'en', 'Artificial human', 'artificial human'),
    ('elf', 'uk', 'Ельф', 'ельф'),
    ('elf', 'en', 'Elf', 'elf'),
    ('high_elf', 'uk', 'Вищий ельф', 'вищий ельф'),
    ('high_elf', 'en', 'High elf', 'high elf'),
    ('wood_elf', 'uk', 'Лісовий ельф', 'лісовий ельф'),
    ('wood_elf', 'en', 'Wood elf', 'wood elf'),
    ('dark_elf', 'uk', 'Темний ельф', 'темний ельф'),
    ('dark_elf', 'en', 'Dark elf', 'dark elf'),
    ('sea_elf', 'uk', 'Морський ельф', 'морський ельф'),
    ('sea_elf', 'en', 'Sea elf', 'sea elf'),
    ('ice_elf', 'uk', 'Крижаний ельф', 'крижаний ельф'),
    ('ice_elf', 'en', 'Ice elf', 'ice elf'),
    ('half_elf', 'uk', 'Напівельф', 'напівельф'),
    ('half_elf', 'en', 'Half-elf', 'half-elf'),
    ('gnome', 'uk', 'Гном', 'гном'),
    ('gnome', 'en', 'Gnome', 'gnome'),
    ('dwarf', 'uk', 'Дворф', 'дворф'),
    ('dwarf', 'en', 'Dwarf', 'dwarf'),
    ('goblin', 'uk', 'Гоблін', 'гоблін'),
    ('goblin', 'en', 'Goblin', 'goblin'),
    ('hobgoblin', 'uk', 'Хобгоблін', 'хобгоблін'),
    ('hobgoblin', 'en', 'Hobgoblin', 'hobgoblin'),
    ('kobold', 'uk', 'Кобольд', 'кобольд'),
    ('kobold', 'en', 'Kobold', 'kobold'),
    ('gremlin', 'uk', 'Гремлін', 'гремлін'),
    ('gremlin', 'en', 'Gremlin', 'gremlin'),
    ('halfling', 'uk', 'Напіврослик', 'напіврослик'),
    ('halfling', 'en', 'Halfling', 'halfling'),
    ('hobbit', 'uk', 'Хоббіт', 'хоббіт'),
    ('hobbit', 'en', 'Hobbit', 'hobbit'),
    ('leprechaun', 'uk', 'Лепрекон', 'лепрекон'),
    ('leprechaun', 'en', 'Leprechaun', 'leprechaun'),
    ('orc', 'uk', 'Орк', 'орк'),
    ('orc', 'en', 'Orc', 'orc'),
    ('half_orc', 'uk', 'Напіворк', 'напіворк'),
    ('half_orc', 'en', 'Half-orc', 'half-orc'),
    ('ogre', 'uk', 'Огр', 'огр'),
    ('ogre', 'en', 'Ogre', 'ogre'),
    ('troll', 'uk', 'Троль', 'троль'),
    ('troll', 'en', 'Troll', 'troll'),
    ('giant', 'uk', 'Велетень', 'велетень'),
    ('giant', 'en', 'Giant', 'giant'),
    ('cyclops', 'uk', 'Циклоп', 'циклоп'),
    ('cyclops', 'en', 'Cyclops', 'cyclops'),
    ('titan', 'uk', 'Титан', 'титан'),
    ('titan', 'en', 'Titan', 'titan'),
    ('fairy', 'uk', 'Фея', 'фея'),
    ('fairy', 'en', 'Fairy', 'fairy'),
    ('fae', 'uk', 'Фейрі', 'фейрі'),
    ('fae', 'en', 'Fae', 'fae'),
    ('pixie', 'uk', 'Піксі', 'піксі'),
    ('pixie', 'en', 'Pixie', 'pixie'),
    ('sprite', 'uk', 'Спрайт', 'спрайт'),
    ('sprite', 'en', 'Sprite', 'sprite'),
    ('nymph', 'uk', 'Німфа', 'німфа'),
    ('nymph', 'en', 'Nymph', 'nymph'),
    ('dryad', 'uk', 'Дріада', 'дріада'),
    ('dryad', 'en', 'Dryad', 'dryad'),
    ('naiad', 'uk', 'Наяда', 'наяда'),
    ('naiad', 'en', 'Naiad', 'naiad'),
    ('sylph', 'uk', 'Сильф', 'сильф'),
    ('sylph', 'en', 'Sylph', 'sylph'),
    ('satyr', 'uk', 'Сатир', 'сатир'),
    ('satyr', 'en', 'Satyr', 'satyr'),
    ('witch', 'uk', 'Відьма', 'відьма'),
    ('witch', 'en', 'Witch', 'witch'),
    ('witcher', 'uk', 'Відьмак', 'відьмак'),
    ('witcher', 'en', 'Witcher', 'witcher'),
    ('wizard', 'uk', 'Чарівник', 'чарівник'),
    ('wizard', 'en', 'Wizard', 'wizard'),
    ('sorcerer', 'uk', 'Чаклун', 'чаклун'),
    ('sorcerer', 'en', 'Sorcerer', 'sorcerer'),
    ('shaman', 'uk', 'Шаман', 'шаман'),
    ('shaman', 'en', 'Shaman', 'shaman'),
    ('druid', 'uk', 'Друїд', 'друїд'),
    ('druid', 'en', 'Druid', 'druid'),
    ('vampire', 'uk', 'Вампір', 'вампір'),
    ('vampire', 'en', 'Vampire', 'vampire'),
    ('half_vampire', 'uk', 'Напіввампір', 'напіввампір'),
    ('half_vampire', 'en', 'Half-vampire', 'half-vampire'),
    ('dhampir', 'uk', 'Дампір', 'дампір'),
    ('dhampir', 'en', 'Dhampir', 'dhampir'),
    ('werecreature', 'uk', 'Перевертень', 'перевертень'),
    ('werecreature', 'en', 'Werecreature', 'werecreature'),
    ('werewolf', 'uk', 'Вовкулака', 'вовкулака'),
    ('werewolf', 'en', 'Werewolf', 'werewolf'),
    ('shapeshifter', 'uk', 'Мінливець', 'мінливець'),
    ('shapeshifter', 'en', 'Shapeshifter', 'shapeshifter'),
    ('metamorph', 'uk', 'Метаморф', 'метаморф'),
    ('metamorph', 'en', 'Metamorph', 'metamorph'),
    ('doppelganger', 'uk', 'Допельгангер', 'допельгангер'),
    ('doppelganger', 'en', 'Doppelganger', 'doppelganger'),
    ('ghost', 'uk', 'Привид', 'привид'),
    ('ghost', 'en', 'Ghost', 'ghost'),
    ('apparition', 'uk', 'Примара', 'примара'),
    ('apparition', 'en', 'Apparition', 'apparition'),
    ('poltergeist', 'uk', 'Полтергейст', 'полтергейст'),
    ('poltergeist', 'en', 'Poltergeist', 'poltergeist'),
    ('zombie', 'uk', 'Зомбі', 'зомбі'),
    ('zombie', 'en', 'Zombie', 'zombie'),
    ('skeleton', 'uk', 'Скелет', 'скелет'),
    ('skeleton', 'en', 'Skeleton', 'skeleton'),
    ('mummy', 'uk', 'Мумія', 'мумія'),
    ('mummy', 'en', 'Mummy', 'mummy'),
    ('lich', 'uk', 'Ліч', 'ліч'),
    ('lich', 'en', 'Lich', 'lich'),
    ('revenant', 'uk', 'Ревенант', 'ревенант'),
    ('revenant', 'en', 'Revenant', 'revenant'),
    ('ghoul', 'uk', 'Упир', 'упир'),
    ('ghoul', 'en', 'Ghoul', 'ghoul'),
    ('specter', 'uk', 'Спектр', 'спектр'),
    ('specter', 'en', 'Specter', 'specter'),
    ('demon', 'uk', 'Демон', 'демон'),
    ('demon', 'en', 'Demon', 'demon'),
    ('archdemon', 'uk', 'Архідемон', 'архідемон'),
    ('archdemon', 'en', 'Archdemon', 'archdemon'),
    ('half_demon', 'uk', 'Напівдемон', 'напівдемон'),
    ('half_demon', 'en', 'Half-demon', 'half-demon'),
    ('imp', 'uk', 'Імп', 'імп'),
    ('imp', 'en', 'Imp', 'imp'),
    ('succubus', 'uk', 'Суккуб', 'суккуб'),
    ('succubus', 'en', 'Succubus', 'succubus'),
    ('incubus', 'uk', 'Інкуб', 'інкуб'),
    ('incubus', 'en', 'Incubus', 'incubus'),
    ('angel', 'uk', 'Ангел', 'ангел'),
    ('angel', 'en', 'Angel', 'angel'),
    ('archangel', 'uk', 'Архангел', 'архангел'),
    ('archangel', 'en', 'Archangel', 'archangel'),
    ('dragon', 'uk', 'Дракон', 'дракон'),
    ('dragon', 'en', 'Dragon', 'dragon'),
    ('wyvern', 'uk', 'Виверна', 'виверна'),
    ('wyvern', 'en', 'Wyvern', 'wyvern'),
    ('drake', 'uk', 'Дрейк', 'дрейк'),
    ('drake', 'en', 'Drake', 'drake'),
    ('griffin', 'uk', 'Грифон', 'грифон'),
    ('griffin', 'en', 'Griffin', 'griffin'),
    ('phoenix', 'uk', 'Фенікс', 'фенікс'),
    ('phoenix', 'en', 'Phoenix', 'phoenix'),
    ('unicorn', 'uk', 'Єдиноріг', 'єдиноріг'),
    ('unicorn', 'en', 'Unicorn', 'unicorn'),
    ('pegasus', 'uk', 'Пегас', 'пегас'),
    ('pegasus', 'en', 'Pegasus', 'pegasus'),
    ('basilisk', 'uk', 'Василіск', 'василіск'),
    ('basilisk', 'en', 'Basilisk', 'basilisk'),
    ('chimera', 'uk', 'Химера', 'химера'),
    ('chimera', 'en', 'Chimera', 'chimera'),
    ('manticore', 'uk', 'Мантикора', 'мантикора'),
    ('manticore', 'en', 'Manticore', 'manticore'),
    ('centaur', 'uk', 'Кентавр', 'кентавр'),
    ('centaur', 'en', 'Centaur', 'centaur'),
    ('hydra', 'uk', 'Гідра', 'гідра'),
    ('hydra', 'en', 'Hydra', 'hydra'),
    ('mermaid', 'uk', 'Русалка', 'русалка'),
    ('mermaid', 'en', 'Mermaid', 'mermaid'),
    ('merman', 'uk', 'Русал', 'русал'),
    ('merman', 'en', 'Merman', 'merman'),
    ('siren', 'uk', 'Сирена', 'сирена'),
    ('siren', 'en', 'Siren', 'siren'),
    ('triton', 'uk', 'Тритон', 'тритон'),
    ('triton', 'en', 'Triton', 'triton'),
    ('selkie', 'uk', 'Селкі', 'селкі'),
    ('selkie', 'en', 'Selkie', 'selkie'),
    ('animal', 'uk', 'Тварина', 'тварина'),
    ('animal', 'en', 'Animal', 'animal'),
    ('sapient_animal', 'uk', 'Розумна тварина', 'розумна тварина'),
    ('sapient_animal', 'en', 'Sapient animal', 'sapient animal'),
    ('magical_animal', 'uk', 'Магічна тварина', 'магічна тварина'),
    ('magical_animal', 'en', 'Magical animal', 'magical animal'),
    ('familiar', 'uk', 'Фамільяр', 'фамільяр'),
    ('familiar', 'en', 'Familiar', 'familiar'),
    ('beastfolk', 'uk', 'Звіролюдина', 'звіролюдина'),
    ('beastfolk', 'en', 'Beastfolk', 'beastfolk'),
    ('catfolk', 'uk', 'Котолюдина', 'котолюдина'),
    ('catfolk', 'en', 'Catfolk', 'catfolk'),
    ('wolfkin', 'uk', 'Вовколюдина', 'вовколюдина'),
    ('wolfkin', 'en', 'Wolfkin', 'wolfkin'),
    ('lizardfolk', 'uk', 'Ящіролюдина', 'ящіролюдина'),
    ('lizardfolk', 'en', 'Lizardfolk', 'lizardfolk'),
    ('golem', 'uk', 'Голем', 'голем'),
    ('golem', 'en', 'Golem', 'golem'),
    ('automaton', 'uk', 'Автоматон', 'автоматон'),
    ('automaton', 'en', 'Automaton', 'automaton'),
    ('homunculus', 'uk', 'Гомункул', 'гомункул'),
    ('homunculus', 'en', 'Homunculus', 'homunculus'),
    ('living_doll', 'uk', 'Оживлена лялька', 'оживлена лялька'),
    ('living_doll', 'en', 'Living doll', 'living doll'),
    ('robot', 'uk', 'Робот', 'робот'),
    ('robot', 'en', 'Robot', 'robot'),
    ('android', 'uk', 'Андроїд', 'андроїд'),
    ('android', 'en', 'Android', 'android'),
    ('cyborg', 'uk', 'Кіборг', 'кіборг'),
    ('cyborg', 'en', 'Cyborg', 'cyborg'),
    ('alien', 'uk', 'Іншопланетянин', 'іншопланетянин'),
    ('alien', 'en', 'Alien', 'alien'),
    ('cosmic_being', 'uk', 'Космічна істота', 'космічна істота'),
    ('cosmic_being', 'en', 'Cosmic being', 'cosmic being'),
    ('energy_lifeform', 'uk', 'Енергетична форма життя', 'енергетична форма життя'),
    ('energy_lifeform', 'en', 'Energy lifeform', 'energy lifeform'),
    ('symbiote', 'uk', 'Симбіонт', 'симбіонт'),
    ('symbiote', 'en', 'Symbiote', 'symbiote'),
    ('hive_organism', 'uk', 'Колективний організм', 'колективний організм'),
    ('hive_organism', 'en', 'Hive organism', 'hive organism'),
    ('elemental', 'uk', 'Елементаль', 'елементаль'),
    ('elemental', 'en', 'Elemental', 'elemental'),
    ('djinn', 'uk', 'Джин', 'джин'),
    ('djinn', 'en', 'Djinn', 'djinn'),
    ('ifrit', 'uk', 'Іфрит', 'іфрит'),
    ('ifrit', 'en', 'Ifrit', 'ifrit'),
    ('nature_spirit', 'uk', 'Дух природи', 'дух природи'),
    ('nature_spirit', 'en', 'Nature spirit', 'nature spirit'),
    ('monster', 'uk', 'Монстр', 'монстр'),
    ('monster', 'en', 'Monster', 'monster'),
    ('otherworldly_being', 'uk', 'Потойбічна істота', 'потойбічна істота'),
    ('otherworldly_being', 'en', 'Otherworldly being', 'otherworldly being')
) AS "seed" ("key", "locale", "name", "normalized_name")
JOIN "species" ON "species"."key" = "seed"."key" AND "species"."user_id" IS NULL
ON CONFLICT ("normalized_name") DO NOTHING;
