export const NOTE_FORM_FIELD_IDS = {
  category: "note-category",
  chapter: "note-chapter",
  chapterError: "note-chapter-error",
  customCategory: "note-custom-category",
  customCategoryError: "note-custom-category-error",
  entity: "note-entity",
  entityError: "note-entity-error",
  entityLabel: "note-entity-label",
  favorite: "note-favorite",
  favoriteHelp: "note-favorite-help",
  page: "note-page",
  pageError: "note-page-error",
  pinned: "note-pinned",
  pinnedHelp: "note-pinned-help",
  savedLocationTitle: "note-saved-location-title",
  spoiler: "note-spoiler",
  spoilerHelp: "note-spoiler-help",
  text: "note-text",
  textCounter: "note-text-counter",
  textError: "note-text-error",
} as const;
